// <auto-generated />
using System;
using FI.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FI.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FiDbContext))]
    [Migration("20260717161450_AddIncidentEvidence")]
    partial class AddIncidentEvidence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FI.Domain.Incidents.Incident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssigneeId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("EventCount")
                        .HasColumnType("integer")
                        .HasColumnName("event_count");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("fingerprint");

                    b.Property<int>("FingerprintAlgorithmVersion")
                        .HasColumnType("integer")
                        .HasColumnName("fingerprint_algorithm_version");

                    b.Property<DateTimeOffset>("FirstSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen");

                    b.Property<Guid>("IntegrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("integration_id");

                    b.Property<DateTimeOffset>("LastSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen");

                    b.Property<int>("ReopenCount")
                        .HasColumnType("integer")
                        .HasColumnName("reopen_count");

                    b.Property<string>("ResolutionSource")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("resolution_source");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("severity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Severity", "Status");

                    b.HasIndex("Status", "LastSeen");

                    b.HasIndex("IntegrationId", "Fingerprint", "FingerprintAlgorithmVersion")
                        .IsUnique();

                    b.ToTable("incidents", (string)null);
                });

            modelBuilder.Entity("FI.Domain.Incidents.IncidentEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CollectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("collected_at");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("incident_id");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("source_type");

                    b.Property<string>("StructuredData")
                        .HasColumnType("jsonb")
                        .HasColumnName("structured_data");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<DateTimeOffset?>("WindowEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_end");

                    b.Property<DateTimeOffset?>("WindowStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_start");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId", "CollectedAt");

                    b.ToTable("incident_evidence", (string)null);
                });

            modelBuilder.Entity("FI.Domain.Ingestion.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("IntegrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("integration_id");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("key_hash");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("key_prefix");

                    b.Property<DateTimeOffset?>("LastRotatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_rotated_at");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<long>("UsageCount")
                        .HasColumnType("bigint")
                        .HasColumnName("usage_count");

                    b.HasKey("Id");

                    b.HasIndex("IntegrationId");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.ToTable("api_keys", (string)null);
                });

            modelBuilder.Entity("FI.Domain.Ingestion.Deployment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChangedConfig")
                        .HasColumnType("jsonb")
                        .HasColumnName("changed_config");

                    b.Property<string>("Commit")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("commit");

                    b.Property<DateTimeOffset>("DeployedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deployed_at");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("environment");

                    b.Property<Guid?>("IntegrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("integration_id");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("service");

                    b.HasKey("Id");

                    b.HasIndex("IntegrationId");

                    b.HasIndex("Service", "Environment", "DeployedAt");

                    b.ToTable("deployments", (string)null);
                });

            modelBuilder.Entity("FI.Domain.Ingestion.IngestionIdempotencyKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid>("IntegrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("integration_id");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("request_hash");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("resource_type");

                    b.HasKey("Id");

                    b.HasIndex("IntegrationId", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("ingestion_idempotency_keys", (string)null);
                });

            modelBuilder.Entity("FI.Domain.Ingestion.Integration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BusinessCriticality")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("business_criticality");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EndpointUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("endpoint_url");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("environment");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("owner");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Environment")
                        .IsUnique();

                    b.ToTable("integrations", (string)null);
                });

            modelBuilder.Entity("FI.Domain.Ingestion.IntegrationEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ApiKeyId")
                        .HasColumnType("uuid")
                        .HasColumnName("api_key_id");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("event_type");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid>("IntegrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("integration_id");

                    b.Property<bool?>("IsSignatureVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_signature_verified");

                    b.Property<bool>("IsTruncated")
                        .HasColumnType("boolean")
                        .HasColumnName("is_truncated");

                    b.Property<int?>("LatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("latency_ms");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<int>("PayloadSizeBytes")
                        .HasColumnType("integer")
                        .HasColumnName("payload_size_bytes");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("RequestRedacted")
                        .HasColumnType("jsonb")
                        .HasColumnName("request_redacted");

                    b.Property<string>("ResponseRedacted")
                        .HasColumnType("jsonb")
                        .HasColumnName("response_redacted");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("IntegrationId", "OccurredAt");

                    b.ToTable("integration_events", null, t =>
                        {
                            t.HasCheckConstraint("ck_events_status_code", "status_code BETWEEN 100 AND 599");
                        });
                });

            modelBuilder.Entity("FI.Domain.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DispatchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dispatched_at");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("message_type");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("FI.Domain.Incidents.Incident", b =>
                {
                    b.HasOne("FI.Domain.Ingestion.Integration", null)
                        .WithMany()
                        .HasForeignKey("IntegrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FI.Domain.Incidents.IncidentEvidence", b =>
                {
                    b.HasOne("FI.Domain.Incidents.Incident", null)
                        .WithMany()
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FI.Domain.Ingestion.ApiKey", b =>
                {
                    b.HasOne("FI.Domain.Ingestion.Integration", null)
                        .WithMany("ApiKeys")
                        .HasForeignKey("IntegrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FI.Domain.Ingestion.Deployment", b =>
                {
                    b.HasOne("FI.Domain.Ingestion.Integration", null)
                        .WithMany()
                        .HasForeignKey("IntegrationId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("FI.Domain.Ingestion.IntegrationEvent", b =>
                {
                    b.HasOne("FI.Domain.Ingestion.Integration", null)
                        .WithMany()
                        .HasForeignKey("IntegrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FI.Domain.Ingestion.Integration", b =>
                {
                    b.Navigation("ApiKeys");
                });
#pragma warning restore 612, 618
        }
    }
}
